name: Selenium Tests with Allure

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install allure-pytest

      - name: Download Allure CLI
        run: |
            ALLURE_VERSION=2.30.0
            wget https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/${ALLURE_VERSION}/allure-commandline-${ALLURE_VERSION}.tgz -O allure.tgz
            tar -zxvf allure.tgz
            sudo mv allure-${ALLURE_VERSION} /opt/allure
            sudo ln -s /opt/allure/bin/allure /usr/bin/allure
            allure --version

          

      - name: Run Pytest with Allure
        run: |
          mkdir -p allure-results
          pytest --alluredir=allure-results

      - name: Generate Allure Report
        run: |
          allure generate allure-results --clean -o allure-report
          # To view the report locally, you can use 'allure serve' instead
          # allure serve allure-results

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
            name: allure-report
            path: allure-report