name: Selenium Tests with Allure

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install allure-pytest

      - name: Install Allure CLI
        run: |
          sudo apt-add-repository ppa:qameta/allure -y
          sudo apt-get update
          sudo apt-get install allure -y

      - name: Run Pytest with Allure
        run: |
          mkdir -p allure-results
          pytest --alluredir=allure-results

      - name: Generate Allure Report
        run: |
          allure generate allure-results --clean -o allure-report
          # To view the report locally, you can use 'allure serve' instead
          # allure serve allure-results
